version: '3.3'

services:
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: php-fpm
    volumes:
      - ${PHP_APPLICATION_FOLDER}:/var/www/html
    networks:
      dcf_network:
        ipv4_address: 172.16.238.10
  php-cli:
    container_name: php-cli
    build:
      context: ./php-cli
      dockerfile: Dockerfile-7.4
    volumes:
      - ${PHP_APPLICATION_FOLDER}:/var/www/html
    networks:
      dcf_network:
        ipv4_address: 172.16.238.11
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ${PHP_APPLICATION_FOLDER}:/var/www/html
    networks:
      dcf_network:
        ipv4_address: 172.16.238.12
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - /data
    networks:
      dcf_network:
        ipv4_address: 172.16.238.13
  node:
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      - "8000:8000"
    tty: true
    stdin_open: true
    volumes:
      - ${JS_APPLICATION_FOLDER}:/home/node/vue-app
    networks:
      dcf_network:
        ipv4_address: 172.16.238.14
networks:
  dcf_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
