version: '3.8'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: php-fpm
      args:
        XDEBUG_ON: 1
    restart: unless-stopped
    volumes:
      - .:/var/www/html
  php-cli:
    container_name: php-cli
    build:
      context: php-cli
    volumes:
      - .:/var/www/html
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - '80'
      - '443'
    volumes:
      - ./nginx/dev.fpm.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - 'redis:/data'
  mysql:
    image: 'mysql:8.0'
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mysql:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  node-cli:
    container_name: node-cli
    build:
      context: node-cli
