version: '3.3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    restart: unless-stopped
    container_name: fpm
    volumes:
      - ${SOURCE_FOLDER}:/var/www/html
  nginx:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ${SOURCE_FOLDER}:/var/www/html
  node:
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile
      args:
        - LOCATION=/home/node/vue-app
    ports:
      - "8081:8080"
      - "8000:8000"
    tty: true
    stdin_open: true
    volumes:
      - ../vue-app:/home/node/vue-app
    environment:
      - NODE_ENV=development