version: '3.3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    restart: unless-stopped
    container_name: fpm
    volumes:
      - ${APPLICATION_CODE_PATH}:/var/www/html
  nginx:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ${APPLICATION_CODE_PATH}:/var/www/html
