version: '3.8'

services:
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      args:
        XDEBUG_ON: 1
    restart: unless-stopped
    container_name: php-fpm
    volumes:
      - .:/var/www/html
  php-cli:
    container_name: php-cli
    build:
      context: ./php-cli
      dockerfile: php-cli/Dockerfile
    volumes:
      - .:/var/www/html
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - .:/var/www/html
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - /data
  node-cli:
    container_name: node-cli
    build:
      context: node-cli
      dockerfile: Dockerfile
